
ALTER TABLE public.mobile_exchanges
  ADD COLUMN IF NOT EXISTS exchange_value NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchange_date DATE NOT NULL DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS accessories TEXT,
  ADD COLUMN IF NOT EXISTS id_proof_type TEXT,
  ADD COLUMN IF NOT EXISTS id_proof_number TEXT;
